- wadm/lib/application.ex
- wadm/lib/config_plan.ex
- wadm/lib/supervisor.ex
- wadm/mix.exs
- wadm/mix.lock
- wadm/test/config_plan_test.exs
e.g. iex -S mix
Signed-off-by: Janitha Jayaweera <janitha_j@hotmail.com>
> Gnat.ConnectionSupervisor starts up when the application startsup

- wadm/lib/supervisor.ex
- wadm/lib/wadm/api/api_server.ex
- wadm/lib/wadm/model/app_spec.ex
- wadm/test/fixtures/simple1.json
- wadm/test/model/validator_test.exs
- wadm/test/model/yaml_json_test.exs
This is, for the moment, a WIP. Once we like the API and shapes, then I can go through and make all the operations real.
> Initial commit of wadm API scaffolding

- oam/simple1.yaml
- oam/simple2.yaml
- wadm/lib/config_plan.ex
- wadm/lib/supervisor.ex
- wadm/lib/wadm/api/api_server.ex
- wadm/lib/wadm/deployments/deployment_monitor.ex
- wadm/lib/wadm/model/actor_component.ex
- wadm/lib/wadm/model/app_spec.ex
- wadm/lib/wadm/model/capability_component.ex
- wadm/lib/wadm/model/link_definition.ex
- wadm/lib/wadm/model/spreadscaler.ex
- wadm/lib/wadm/model/store.ex
- wadm/lib/wadm/model/weighted_target.ex
- wadm/mix.exs
Initial implementation of CRUD functionality on app specs. Also implements deploy/undeploy functionality on the agent process, though the agent process currently does nothing.
> Preliminary implementation of model store and retrieve

- EVENTS.md
- wadm/lib/wadm/api/api_server.ex
- wadm/lib/wadm/deployments/cloud_events.ex
- wadm/lib/wadm/deployments/deployment_monitor.ex
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
> Adding event emission

- wadm/lib/wadm/lattice_supervisor.ex
- wadm/mix.exs
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
> Listen for RPC events on different topic

- Cargo.lock
- Cargo.toml
- bin/logging.rs
- bin/main.rs
- src/consumers/commands.rs
- src/consumers/events.rs
- src/consumers/manager.rs
- src/consumers/mod.rs
Puts together something for actually doing work and managing several loops. This makes it easier to encapsulate the actual work we have to do down the line
> feat(*): Cleaner task running

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- Makefile
- bin/main.rs
- src/events/data.rs
- src/events/types.rs
- src/lib.rs
- src/storage/mod.rs
- src/storage/nats_kv.rs
- src/storage/state.rs
- tests/helpers.rs
- tests/storage_nats_kv.rs
Add code to support storing state (in a somewhat general fashion), and more specifically lattice state in NATS KV.
#45 
`next`
Consumers will be able to use a `wadm` flow that relies on NATS KV state.
TBD
TBD
TBD
> feat: track lattice state in kv

- .github/workflows/test.yml
- Cargo.lock
- src/events/types.rs
- src/lib.rs
- src/storage/mod.rs
- src/storage/reaper.rs
- src/test_util.rs
- src/workers/event.rs
- tests/helpers.rs
- tests/storage_nats_kv.rs
This adds a lot of unit tests to make sure state is generated properly. They are quite long but they walk through a roughly lifelike flow of events
> feat(event): Full state unit tests

- Cargo.lock
- Cargo.toml
- bin/connections.rs
- bin/main.rs
- src/commands/mod.rs
- src/lib.rs
- src/model/mod.rs
- src/scaler/simplescaler.rs
- src/workers/command.rs
- src/workers/mod.rs
- tests/command_consumer_integration.rs
- tests/command_worker_integration.rs
- tests/helpers.rs
This adds a worker that actually translates commands into lattice ctl operations. It also starts the work of creating a control client per lattice as needed
Closes #50
> feat(workers): Adds a new command worker

- src/model/mod.rs
- src/scaler/manager.rs
- src/scaler/spreadscaler/link.rs
- src/scaler/spreadscaler/mod.rs
- src/scaler/spreadscaler/provider.rs
This PR implements a Link spreadscaler, which simply waits until it can find the proper actor and provider IDs before publishing a link. Currently this does not check to see if the link exists already, which is why this is marked as draft and there's a TODO comment
#51 
0.4.0
Links!
Looking to add basic unit tests to validate functionality
> feat(*) Link "spreadscaler" implementation

- Cargo.lock
- src/events/data.rs
- src/events/types.rs
- src/model/mod.rs
- src/scaler/manager.rs
- src/scaler/spreadscaler/link.rs
- src/scaler/spreadscaler/mod.rs
- src/scaler/spreadscaler/provider.rs
- src/server/types.rs
- src/workers/event.rs
- test/data/events.json
There are some e2e tests needed here, but this should be good enough for an alpha release
> fix(*): Fixes various issues we had while debugging wadm for real

- Cargo.lock
- Cargo.toml
- LICENSE
- README.md
Also adds some more debugging for a weirdly failing test
> docs(*): Adds known issues to readme

- .github/workflows/e2e.yml
- .gitignore
- Cargo.toml
- Makefile
- src/lib.rs
- src/scaler/spreadscaler/mod.rs
- src/server/types.rs
- test/data/simple.yaml
- test/docker-compose-e2e.yaml
- tests/e2e.rs
- tests/e2e_multiple_hosts.rs
This adds some basic scaffolding and a pipeline for running e2e tests. It doesn't contain all e2e tests we should write, but has all the scaffolding and the most simple test put together and running
> feat(tests): Adds e2e test scaffolding

- Cargo.lock
- Cargo.toml
- README.md
- bin/main.rs
- src/consumers/manager.rs
- src/scaler/spreadscaler/link.rs
- src/scaler/spreadscaler/mod.rs
- src/scaler/spreadscaler/provider.rs
- src/storage/reaper.rs
- src/workers/command.rs
- test/data/complex.yaml
- test/data/host_stop.yaml
- test/data/lotta_actors.yaml
- test/docker-compose-e2e.yaml
- tests/command_worker_integration.rs
- tests/e2e.rs
- tests/e2e_multiple_hosts.rs
- tests/event_consumer_integration.rs
- tests/helpers.rs
This PR adds a full e2e test suite along with bug fixes I found along the way. It also polishes up the README and sets the version to 0.4.0 in preparation for the full release
Closes #53
> feat(tests): Finishes e2e tests

- .github/workflows/release.yml
- Dockerfile
Also makes image building faster by copying the already built binary
Closes #127
> Adds support for building arm image

- Cargo.lock
- Cargo.toml
> chore: bumped to 0.5.0-alpha.3

- Cargo.lock
- Cargo.toml
Signed-off-by: Brooks Townsend <brooks@cosmonic.com>
> chore: bump version for 0.5.0-rc.1

- src/workers/event.rs
This PR addresses a race condition where, during an upgrade, we published cleanup commands _before_ notifying other wadm instances that they need to upgrade their scalers. This would manifest itself by stopping old resources and then immediately restarting those old resources before the new scalers are created, which effectively makes the upgrade fail.
N/A
v0.5.0-alpha.5
Users of alpha.4 may see some inconsistent upgrades
> fix(upgrades): run cleanup commands after adding scalers

- Cargo.lock
- Cargo.toml
This PR bumps to 0.5.0 for release! :tada:
> chore: bump to 0.5 for release

- Cargo.lock
- Cargo.toml
Signed-off-by: Brooks Townsend <brooks@cosmonic.com>
> chore: bump to 0.6.0 for release

- src/server/handlers.rs
Outputs of the `wash app` commands (mainly `put` and `deploy`) do not include the manifest name. Including the manifest name is an overall DX improvement of the `wash` cli.
#175 
v0.6.0
just a QOL change for the `wash` cli
> feat(server): improved output messages for model operations

- Cargo.lock
- Cargo.toml
- src/workers/event.rs
This also removes some comments we missed in a previous PR
> chore(*): Bumps version to 0.8.0-rc.1

- src/server/types.rs
This marks the VersionInfo and ModelSummary types as Clone, which makes them easier to work with when including them in collections (ex. storing in a Vec).
> Derive VersionInfo and ModelSummary types as Clone

- Cargo.lock
- Cargo.toml
- src/server/handlers.rs
Update dependencies, most importantly update `async-nats` to `0.33`
> build: update dependencies

- Cargo.lock
- Cargo.toml
Bumping for ~alpha~ release candidate of 0.10
> release: v0.10.0-rc1

- Cargo.lock
- Cargo.toml
This PR bumps to release v0.10.0
> release: v0.10.0

- Cargo.lock
- Cargo.toml
This PR bumps to an alpha release of 0.11.0, which will have compatibility with wasmcloud 1.0.
> chore: bump to v0.11.0-alpha.1

- src/scaler/manager.rs
This PR changes the automatic component ID generation to be calculated based on the model name and the component name, rather than the model name and a sanitized version of the reference. In general this creates a more predictable ID and a much shorter one as well. This should also be more intuitive to the user as to how we calculate that ID, and if it's still too long, encourage specifying your own.
| Before | After | 
| --- | --- | 
| mymodelname-wasmcloud_azurecr_io_echo_0_3_4 | mymodelname-echo | 
For some background motivation, the component ID needs to be unique for an individual entity on the lattice (no matter where it runs). Computing this ID automatically from these two fields ensures that we're generating an ID that's unlikely to collide with any user specified ID, and is not …
> fix: calculate component ID from model and name

- bin/nats.rs
This PR ensures when wadm starts that it enforces that its streams have the correct subjects. We could check for additional configuration values on the stream, however I don't want to clobber over configuration when someone decides in production to replicate the stream, for example.
#241 changed the subject of the mirror stream and we need to have the updated suffix for events to work.
v0.11.0-alpha.3
> fix: ensure streams have updated subjects

- Cargo.lock
- Cargo.toml
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
> chore: bump to v0.11.0 for release

- src/scaler/daemonscaler/mod.rs
- src/scaler/daemonscaler/provider.rs
- src/scaler/spreadscaler/mod.rs
- src/scaler/spreadscaler/provider.rs
- src/server/handlers.rs
> chore: fix clippy lints

- Cargo.lock
- Cargo.toml
Bringing in the version bump from the cherry picked https://github.com/wasmCloud/wadm/tree/release/v0.11.2
> chore: bump to v0.11.2

- README.md
- oam/hello.yaml
Updates manifest example in readme to 1.0 manifest format and tidies up some links and language.
> docs(readme): Update manifest example and language for 1.0

- Cargo.lock
- Cargo.toml
- crates/wadm/Cargo.toml
We missed the crate bump when we did the other version bump
> fix(*): Bumps wadm crate version

- Cargo.lock
- crates/wadm-client/Cargo.toml
- crates/wadm-client/src/topics.rs
This PR corrects the model list topic used in the wadm client crate.
wadm-client v0.1.1
> fix(client): app list topic

- Cargo.lock
- Cargo.toml
- crates/wadm/Cargo.toml
Bumping to release #297
#297
wadm v0.12.1
> chore: bump to v0.12.1 for release

- Cargo.lock
- crates/wadm-client/Cargo.toml
- crates/wadm-client/src/topics.rs
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
This PR corrects the delete topic in the wadm-client. I sanity checked the rest of the topics since this is the second patch fix to go in but we should be good to go with this.
> fix(client): correct delete topic

- crates/wadm/src/server/handlers.rs
This PR fixes an issue where the server handler couldn't support an empty delete payload.
Fixes https://github.com/wasmCloud/wasmCloud/issues/2342
wadm v0.12.1
> fix(wadm): support empty delete payload

- Cargo.lock
- Cargo.toml
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
> chore(wadm): update to v0.12.2

- README.md
- crates/wadm/oam.schema.json
- oam/hello.yaml
- oam/kvcounter.yaml
- oam/oam.schema.json
- oam/sqldbpostgres.yaml
- test/data/events.json
- tests/fixtures/manifests/custom-interface.wadm.yaml
- tests/fixtures/manifests/dangling-link.wadm.yaml
- tests/fixtures/manifests/misnamed-interface.wadm.yaml
- tests/fixtures/manifests/simple.wadm.yaml
- tests/fixtures/manifests/unknown-package.wadm.yaml
Signed-off-by: Bailey Hayes <behayes2@gmail.com>
We support both instances and replicas as a field for scaling components. The problem with this is that it causes inconsistencies for downstream tools like the operator. We should move to deprecate replicas. This is the first step to do this.
`next`
None: doc and example changes.
> fix: use instances in all examples

- .github/workflows/release.yml
This PR fixes using a short lived token in favor of the token associated with this repository.
> ci(release): use GITHUB_TOKEN to release

- .github/workflows/e2e.yml
- .github/workflows/release.yml
These needed to be bumped together.
Supercedes https://github.com/wasmCloud/wadm/pull/322 and https://github.com/wasmCloud/wadm/pull/320
> ci(e2e,release): update upload/download to v4

- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
- crates/wadm-types/Cargo.toml
- crates/wadm-types/src/lib.rs
- crates/wadm-types/src/validation.rs
- crates/wadm/Cargo.toml
- crates/wadm/src/scaler/manager.rs
- crates/wadm/src/scaler/secretscaler.rs
- crates/wadm/src/storage/snapshot.rs
- crates/wadm/src/test_util.rs
- crates/wadm/src/workers/event_helpers.rs
- crates/wadm/test/data/all_hosts.yaml
- oam.schema.json
- tests/fixtures/manifests/policy.wadm.yaml
- tests/fixtures/manifests/simple.wadm.yaml
This PR takes care of necessary crate bumps to release wadm 0.13.0, and clients/types 0.2.0. Leaving as draft as I continue to validate the functionality here and take a look at some of the code.
Note that I've filed #347 since that hasn't been taken care of yet.
> chore(*): prepare 0.13

- crates/wadm/src/server/handlers.rs
This PR replaces a previous check for uniqueness of image references for checking for uniqueness of component IDs assigned to components or providers.
wadm v0.13.0
> feat(server)!: ensure claimed ID is uniquely deployed

- README.md
Just language updates to the README
> chore: update README to be more direct

- Cargo.lock
- Cargo.toml
- tests/command_consumer_integration.rs
- tests/command_worker_integration.rs
- tests/event_consumer_integration.rs
- tests/helpers.rs
This replaces a bunch of the `wash up` based test setup with [`testcontainers`](https://github.com/testcontainers/testcontainers-rs/) based setup instead.
Closes #353
> chore: Replace wash up with testcontainers

- crates/wadm/src/storage/snapshot.rs
This PR changes the snapshot store to use cached links in the case of the last host in the lattice stopping, preventing 3 error logs & a failure to reconcile.
#345
next patch release of wadm
> fix(#345): use cached links when req fails

- crates/wadm/src/server/handlers.rs
This is a temporary fix that ensures that the older `status` parameter in the `ModelSummary` struct doesn't include the new status, `Waiting`, at least until we release 0.14.0. This is to give developers a minor version to bring in the new change.
> fix(server): use backwards compatible undeployed

- oam.schema.json
Manifest name shows up in IDE's as "Manifest" which isn't very helpful.
nada
> chore(schema): change name and description on json schema

- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
- crates/wadm-types/Cargo.toml
This PR bumps all of the crates a minor version to account for changes and prepare for release.
> release: bump crates for release

- .github/workflows/release.yml
- Dockerfile.wolfi
> feat: Add wolfi image

- Cargo.lock
- crates/wadm/src/scaler/mod.rs
- crates/wadm/src/storage/state.rs
- crates/wadm/src/workers/event.rs
- tests/command_worker_integration.rs
- tests/e2e.rs
- tests/e2e_multiple_hosts.rs
> chore(deps): update to ctrl iface 2.1.0

- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
- crates/wadm-types/Cargo.toml
> release: Bump wadm client and types

- Cargo.lock
- Cargo.toml
Bumps wadm to 0.16 for releasing the latest control interface compatibility
> release(wadm): v0.16.0

- Cargo.lock
- Cargo.toml
Incorporates #448 into a `wadm` release
> release: Bump wadm to 0.17.0

- MAINTAINERS.md
> chore(MAINTAINERS): add organizations

- Cargo.lock
- Cargo.toml
Setting up release for 0.18.0-rc.1 testing w/ shared providers
> release(wadm): v0.18.0-rc.1

- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
> release(wadm): 0.18, types and client 0.7

- Cargo.lock
> chore: Bump wascap to 0.15.2

- Cargo.lock
- Cargo.toml
> chore: Bump `wasmcloud-secrets-types`

- .github/workflows/release.yml
Judging by some of the failures from recent CI, something changed in upstream enough that we should pin the zig version to the latest stable version.
> chore(ci): pin zig to latest stable version

- Cargo.lock
- crates/wadm-client/Cargo.toml
> chore(wadm-client): prune unused dependencies

- Cargo.lock
- Cargo.toml
> chore(wadm-cli): prune unused dependencies

- Cargo.lock
Fixes [`RUSTSEC-2024-0402`](https://rustsec.org/advisories/RUSTSEC-2024-0402.html) / [`GHSA-wwq9-3cpr-mm53`](https://github.com/advisories/GHSA-wwq9-3cpr-mm53)
> fix: RUSTSEC-2024-0402

- .github/workflows/scorecard.yml
Seems reasonable to bring this into wadm as well.
> chore: Add OSSF Scorecard workflow

- .github/workflows/scorecard.yml
It appears I had a tab when it should've been spaces.
> chore: Fix scorecard workflow spacing

- SECURITY.md
> chore: Add Security Policy with link to the main repository

- .github/workflows/chart.yml
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/wit-wadm.yaml
> chore(ci): Pin GitHub Actions dependencies

- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
- crates/wadm-types/Cargo.toml
This PR bumps all the crate versions for a subsequent release.
> release(*): bump versions

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
- crates/wadm-types/Cargo.toml
- crates/wadm-types/src/validation.rs
- crates/wadm/src/lib.rs
- crates/wadm/src/scaler/daemonscaler/provider.rs
- crates/wadm/src/scaler/spreadscaler/provider.rs
- crates/wadm/src/workers/event.rs
- flake.lock
- src/main.rs
- tests/event_consumer_integration.rs
- tests/validation.rs
I also did a little housekeeping here to fix a bunch of clippy lints and updated the flake inputs
> chore: Bumps versions for patch release

- .github/release.yml
- Cargo.lock
- Cargo.toml
- crates/wadm-client/Cargo.toml
- crates/wadm-types/Cargo.toml
This PR patch bumps all crates for release.
Releasing #585
> chore: patch all for release

- charts/wadm/Chart.yaml
- charts/wadm/templates/_helpers.tpl
- charts/wadm/values.yaml
Support all [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) and additional labels to add to all resources
> feat(helm): Kubernetes labels

- .github/workflows/release.yml
Per https://github.com/goto-bus-stop/setup-zig/issues/72, `goto-bus-stop/setup-zig` is effectively no longer maintained, while [mlugg/setup-zig](https://github.com/mlugg/setup-zig) is under active development still.
> chore: Switch to mlugg/setup-zig action
