wasmCloud/wadm

wadm/lib/config_plan.ex, wadm/lib/supervisor.ex, wadm/lib/wadm/lattice_supervisor.ex
This PR renames env vars to have a standard `WADM_` prefix and introduces a port for cluster gossiping. The default is the default as specified in https://hexdocs.pm/libcluster/Cluster.Strategy.Gossip.html, but it can be configured. There are more cluster variables that can be configured but I've left them out until there's a need for them
=> Cluster gossip configuration, renamed env vars

wadm/lib/wadm/api/api_server.ex, wadm/mix.exs
This PR corrects a few event arguments that were ordered incorrectly, or in the `version` case sending the entire model instead of just the version.
Since #26 is now merged into main, this version may need to bump to `0.2.0`. Thoughts @autodidaddict ?
=> Corrected argument orders for events

wadm/README.md, wadm/lib/wadm/deployments/deployment_monitor.ex, wadm/lib/wadm/model/store.ex, wadm/lib/wadm/nats.ex, wadm/lib/wadm/reconciler/traits.ex, wadm/mix.exs, wadm/test/reconciler/linkdefs_test.exs
This PR:
- Adds more instructions into the README for how to run wadm
- Wraps NATS calls in the safe wrapper like host_core to ensure no crashes when connection is lost
- Reduces the startup time by a few seconds, initiating the host ping quicker
- Refactors a few functions, notably allowing a reconcile to perform specific actions or calculate what to do
- Allows linkdefs to be put during the reconciliation loop
The last point is a big one, since it was a deliberate decision to only issue lattice control commands when wadm is not reconciling to avoid thrashing. I still think it's a good idea to prevent starting and stopping actors/providers because those are _not_ idempotent and change the state of the lattice in a way that can thrash. However, link definitions are idempotent and can be …
=> Allow linkdefs to put during reconciliation loop

.github/workflows/release.yml, wadm/Dockerfile
Fixes issues causing the failure in https://github.com/wasmCloud/wadm/actions/runs/2876471664
It both requires adding a C++ toolchain into the build image and setting up the windows runner to know where the build toolchain is (we've done this same fix for wasmcloud-otp)
=> Setup c++ toolchains for snappyer

.github/workflows/build.yml, README.md, wadm/README.md, wadm/lib/config_plan.ex, wadm/lib/wadm/lattice_supervisor.ex, wadm/mix.exs
Previously the port would be interpreted as a string which fails to connect. Additionally, I simplified the secret storage to just `seed` instead of `nkey_seed`
edit: Also I noticed that NATS wasn't running for the tests so they were all technically failing. Added that step
=> Fixed a few logic errors in config

wadm/lib/wadm/model/decoder.ex, wadm/lib/wadm/reconciler/app_spec.ex, wadm/test/fixtures/mixed_spreads.yaml, wadm/test/fixtures/no_spreads.yaml, wadm/test/model/validator_test.exs
This PR also serves as a proposal. As things currently stand, a user
has to specify a full set of requirements and name in order to deploy
multiple replicas:
```yaml
- type: spreadscaler
properties:
replicas: 1
spread:
- name: customersclinicapp
requirements:
app: petclinic
```
However, if a user wanted to just run a certain number of replicas, without
setting up tagged hosts (e.g. when running `wash up`), they would get an
error about having an invalid trait if the `spread` key wasn't included. This
PR adds support for setting only the `replicas` field when you don't care
about requirements:
```yaml
- type: spreadscaler
properties:
replicas: 1
```
It also allows for `nil` or empty requirements fields for when you might want
to specify weight for all hosts and then run some on another …
=> feat(*): Add better support for non-conditional spreadscaler

.github/workflows/test.yml, Cargo.lock, Cargo.toml, bin/main.rs, bin/nats.rs, src/events/data.rs, src/events/types.rs, src/storage/mod.rs, src/storage/nats_kv.rs, src/storage/state.rs, tests/event_consumer_integration.rs, tests/storage_nats_kv.rs
This is part of my work for actually generating the lattice state, however I realized that in the previous task we didn't really specify how we were going to save the data. As I started to work on storing lattice state, it became obvious what we had wasn't a good fit. So I refactored to better fit what we needed and took a little bit of time to make the patterns match what we had in other places (such as taking a `Store`, rather than constructing the client and the bucket within the store)
I updated the integration tests to make sure data could be stored and retrieved
Verification was done through integration tests
=> ref(storage): Refactors store to better fit the data structure we need

Cargo.lock, Cargo.toml, oam/simple1.json, src/events/mod.rs, src/events/parser.rs
Parses OAM manifests for warm. Supports YAML and JSON configurations and converts them into in memory Rust structs.
#43 
next
Will support parsing option for manifests
Unit tests added
test_oam_deserializer
test_oam_serializer
NA
Manually verified with existing YAML/JSON files.
=> Added parser to serialize and deserialize OAM manifests

oam/simple1.json, oam/simple1.yaml, oam/simple2.yaml, src/events/parser.rs
Modified spread requirements to be a simple Map
Modified tests and OAM manifests to contain strings only
Extension to #66 that changes Spread requirements to be a BTreeMap with keys and values as <String, String> instead of the earlier <String, SpreadRequirementValues> which consisted an enum of a variety of values. 
Modified the sample manifests to contain string values as well instead of the earlier present boolean values.
#66 
next
If other components are using the manifests, they need to accommodate for the new values in them.
Unit tests added
Unit test modified -
test_oam_deserializer
test_oam_serializer
NA
Manually verified the test results.
=> Modified spread requirements to be a simple Map

.github/workflows/test.yml, Cargo.lock, Cargo.toml, tests/command_consumer_integration.rs, tests/event_consumer_integration.rs, tests/helpers.rs
re-enable the tests in `event_consumer_integration.rs`
#47 
`next`
Customers can effectively test event consumers.
N/A
Integration tests in `event_consumer_integration.rs` were run
Tests were run locally and in CI.
=> fix(ci): event_consumer_integration tests

Cargo.lock, Cargo.toml, bin/main.rs, src/lib.rs, src/model/internal.rs, src/model/mod.rs, src/server/handlers.rs, src/server/mod.rs, src/server/parser.rs, src/server/types.rs, tests/api_model_operations.rs
This PR implements the wadm NATS api and backend storage for the manifests. Anywhere I have deviated from the current wadm_0.3 api, I have tried to document it with a note so we can update the docs later. In a follow up PR, I will finish implementing the actual deployment operations of the API. For now, I wanted to make sure this didn't get _too_ big to review.
Partially closes #43 and closes #44
=> feat(api): Implements all model operations

oam/custom.yaml, src/model/internal.rs, src/model/mod.rs, src/server/handlers.rs, src/server/mod.rs, src/server/types.rs, tests/api_model_operations.rs
Please note that this doesn't try to do any sort of notification event when something is deployed. That will have to be handled later
=> feat(*): Handle deploy operations

src/lib.rs, src/scaler/mod.rs, src/scaler/simplescaler.rs, src/storage/mod.rs, src/storage/nats_kv.rs, src/storage/reaper.rs, src/test_util.rs, src/workers/event.rs, tests/storage_nats_kv.rs
@thomastaylor312 
The Scaler trait, which defines a trait that can be implemented to handle the scaling of a single component (be it actors, linkdefs, or providers) looks like this:
```rust
#[async_trait]
pub trait Scaler {
type Config: Send + Sync;
/// Provide a scaler with configuration to use internally when computing commands
fn update_config(&mut self, config: Self::Config) -> Result<bool>;
/// Compute commands that must be taken given an event that changes the lattice state
async fn handle_event<S: ReadStore + Send + Sync>(
&self,
store: S,
event: Event,
) -> Result<HashSet<Command>>;
/// Compute commands that must be taken to achieve desired state as specified in config
async fn reconcile<S: ReadStore + Send + Sync>(&self, store: S) -> Result<HashSet<Command>>;
}
```
Essentially, …
=> Scaler trait and sample implementation with a SimpleScaler

Cargo.lock, Cargo.toml, bin/connections.rs, bin/main.rs, bin/nats.rs, bin/observer.rs, src/consumers/commands.rs, src/consumers/events.rs, src/consumers/manager.rs, src/consumers/mod.rs, src/lib.rs, src/model/mod.rs, src/nats_utils.rs, src/server/mod.rs, src/server/types.rs, src/storage/reaper.rs, tests/api_model_operations.rs, tests/event_consumer_integration.rs, tests/helpers.rs
This commit makes it so that wadm automatically watches for new lattices to appear and then manages them. As part of this, it made sense to actually make sure this is mutlitenant ready as well. So this implements the functionality to properly observe for multitenant (read: cross account importing) architectures.
Not gonna lie that some of the stuff to start watching pre-observed lattices is a bit messy, but I did test it out and it is real slick
=> feat(*): Automatically observe lattices

src/commands/mod.rs, src/model/mod.rs, src/scaler/mod.rs, src/scaler/simplescaler.rs, src/scaler/spreadscaler.rs, src/storage/mod.rs, src/storage/reaper.rs, src/storage/state.rs, src/test_util.rs, src/workers/command.rs, src/workers/event.rs, src/workers/mod.rs, tests/command_consumer_integration.rs, tests/command_worker_integration.rs, tests/storage_nats_kv.rs
Fixes #51 
This PR adds the `ActorSpreadScaler`, an implementation of the `Scaler` trait which spreads replicas of actors across a list of spread requirements. It does not attempt to evenly spread on hosts that match requirements, as that's more complicated and better suited for another Scaler implementation.
Currently marking as ready for review, but two (or three?) outstanding things I need to address
- After rebasing and adding in #76, this functionality was added _and_ required a ton of work to refactor our current state to take into account instance IDs and annotations.
Added multiple unit tests to ensure proper functionality of the spreadscaler
I ran the tests but did not run for reals since the mechanism for publishing commands isn't …
=> (feat) Implement the ActorSpreadScaler

Cargo.lock, Cargo.toml, bin/main.rs, bin/observer.rs, src/events/types.rs, src/lib.rs, src/mirror/mod.rs, src/server/handlers.rs, src/server/mod.rs, src/server/notifier.rs, src/workers/event.rs, test/data/events.json, tests/api_model_operations.rs
Please note that this is a bit big because I had to have a stream that combined internal wadm events with wasmbus ones. However, I did realize that we only care about streams for their configuration and delivery guarantees, and not for their storage capabilities. Because of this, we don't actually have to have the users configure the streams beforehand. So while this adds one more stream to manage combining the two topics (until nats 2.10 comes out and we move to it), the user no longer has to configure any of them.
Closes #49
=> feat(*): Notifies on manifest deployment

Cargo.lock, Cargo.toml, bin/main.rs, bin/nats.rs, bin/observer.rs, src/commands/mod.rs, src/consumers/manager.rs, src/events/types.rs, src/lib.rs, src/model/internal.rs, src/model/mod.rs, src/publisher.rs, src/scaler/manager.rs, src/scaler/mod.rs, src/scaler/simplescaler.rs, src/scaler/spreadscaler.rs, src/server/handlers.rs, src/server/mod.rs, src/server/notifier.rs, src/storage/reaper.rs, src/test_util.rs, src/workers/event.rs, src/workers/event_helpers.rs, src/workers/mod.rs, test/data/events.json, tests/api_model_operations.rs, tests/event_consumer_integration.rs, tests/helpers.rs
This is a giant PR because a lot of debugging happened. Most of this stuff is Real Code we will keep around. However, there is one big hacky thing to point out. In order to handle Actor Start/Stop events, we had to introduce the idea of a backoff, similar to what is done in wadm 0.3. This method definitely puts the "eventual" in eventual consistency, particularly with high replica counts, but it does work. This backoff is not needed for linkdef or provider scalers. The reason why this was needed was due to there being no way for identifying "groups" (for lack of a better term) of started and stopped events. We ended up with a stream of events with a non-deterministic end. The real solution here would be to update our actor started/stopped events to just emit a single event when a …
=> feat(*): Integrates in the scalers into the event workers

Cargo.lock, Cargo.toml
This makes it so we don't release a full version when we merge to main. Also removes the temp dependency we had on my branch.
=> chore(*): Changes wadm version to alpha

Makefile, src/server/handlers.rs, src/server/mod.rs, src/server/types.rs, tests/api_model_operations.rs
This PR makes a few changes to the wadm API, along with a forthcoming PR in `wash`, to ensure you can use `wash` 
(pr) https://github.com/wasmCloud/wash/pull/520
v0.4.0
Consumers can use `wash` to interact with wadm 0.4
I manually ran the happy paths through the API interactions, but I haven't tested them all yet so leaving as draft until I can validate all of the commands through successful and failure paths.
=> feat(*) wash support

oam/simple2.yaml, src/model/mod.rs, src/scaler/manager.rs, src/scaler/spreadscaler/link.rs
This PR allows two more things in the wadm manifest to be replaced by default values.
1. Linkdef values (as you do not need values to create a linkdef)
2. Provider spreadscaler properties (as it's just a little verbose)
The first is desired behavior, but the second is a preference and worth discussion. I like it because it can reduce this:
```yaml
- name: httpclient
type: capability
properties:
image: wasmcloud.azurecr.io/httpclient:0.5.3
contract: wasmcloud:httpclient
traits:
- type: spreadscaler
properties:
replicas: 1
- name: blobstore
type: capability
properties:
image: wasmcloud.azurecr.io/blobstore_fs:0.1.0
contract: wasmcloud:blobstore
traits:
- type: spreadscaler
properties:
replicas: 1
- name: messaging
type: capability
properties:
image: …
```
=> Allow more optional manifest things

.devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/install.sh, README.md
This PR adds a simple devcontainer that installs `wash` and `wadm` so that people can run through the example without installing anything locally, if they prefer. Additionally it adds an "Open in Codespaces" badge, which is slick.
We install `wash` directly using `cargo` as we have some commands we need to change + release in wash, but wadm is downloaded from the github release directly
=> feat(*) simple devcontainer

Makefile, README.md, bin/main.rs, bin/observer.rs, src/model/internal.rs, src/scaler/manager.rs, src/server/handlers.rs, src/server/mod.rs, src/server/storage.rs, src/server/types.rs, test/data/all_hosts.yaml, tests/api_model_operations.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/event_consumer_integration.rs, tests/helpers.rs
This solved the problem where you could really only update one manifest at a time per lattice. Please note that this has some added e2e tests, but those are currently commented out as they are waiting on some of our other work for removing jitter from starting actors (which is landing in the new host version and in wadm fairly soon)
=> ref(server): Refactors storage for manifests 

oam/provider_config.yaml, src/commands/mod.rs, src/model/mod.rs, src/scaler/manager.rs, src/scaler/spreadscaler/provider.rs, src/server/handlers.rs, src/workers/command.rs, tests/api_model_operations.rs, tests/command_worker_integration.rs
Adds support for passing a string encoded config or an optional json encoded config through to a provider. This includes an additional example manifest and tests
Closes #102
=> feat(*): Adds support for provider config

.devcontainer/install.sh, Cargo.lock, Cargo.toml, Makefile, README.md, bin/main.rs, src/commands/mod.rs, src/events/data.rs, src/events/types.rs, src/model/mod.rs, src/scaler/manager.rs, src/scaler/mod.rs, src/scaler/simplescaler.rs, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/server/notifier.rs, src/storage/state.rs, src/test_util.rs, src/workers/command.rs, src/workers/event.rs, src/workers/event_helpers.rs, src/workers/mod.rs, test/docker-compose-e2e.yaml, tests/e2e.rs
There's one or two more TODOs that I've outlined below, but I'm marking as ready for review to get some input around the rest of the methodology. 
This PR:
Currently, Scalers (particularly the ActorSpreadScaler) are prone to jitter and difficulty actually converging on proper state when you run many (10+) copies of an actor. They are handling each event as it comes in, and we added a very coarse backoff mechanism to account for this but it still creates difficulties.
Will file issue soon to make state only update on plural events.
next alpha release
Consumers will notice that wadm feels more responsive at reconciling
This feature is large enough that it probably warrants some tests to verify behavior around expected events.
I've applied …
=> feat(*) Remove jitter with plural events and expected events

src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/workers/event.rs, test/data/all_hosts.yaml, test/docker-compose-e2e.yaml
This PR contains a couple small changes I discovered while manually testing, but the large change is around the scaler algorithm for providers. Now a provider scaler will consider its job done if _any_ provider matching what it is expecting to be running.
Closes #106
=> feat(scaler): Accounts for other providers running the lattice

Cargo.lock, Cargo.toml, src/consumers/commands.rs, src/consumers/events.rs, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/mod.rs, src/server/storage.rs, src/storage/nats_kv.rs, src/test_util.rs, src/workers/event_helpers.rs, tests/event_consumer_integration.rs
This PR points async_nats at main after https://github.com/nats-io/nats.rs/commit/71cfb61d30a3ecae375685b140d8fe26f4cdac84 merged. Will be in draft until that release stabilizes and the below issues can merge.
Depends on https://github.com/wasmCloud/control-interface-client/pull/49
next
Wadm will properly store/update state in environments where jetstream domains are specified
=> Bumped nats and nkeys to fix update bug

Cargo.lock, bin/main.rs, src/scaler/manager.rs, src/server/handlers.rs, src/server/mod.rs, src/server/storage.rs, test/docker-compose-e2e-multitenant.yaml, test/nats/nats-test.conf, tests/api_model_operations.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/e2e_multitenant.rs, tests/event_consumer_integration.rs
This PR ensures we are storing and querying manifests based on an account prefix if running in multitenant mode. This ensures that accounts can only access and modify manifests that are specifically bound to that account, rather than simply using a global lattice ID.
Due to possible edge cases, it's still recommended to keep lattice prefixes globally unique between accounts, as there are not e2e tests at this time to verify that functionality works without issues. This PR at least implements the portion of that that constrains manifests from conflicting between accounts.
#132
v0.5.0
Multitenancy hasn't released yet so this shouldn't affect consumers, however they will need to examine the account prefixed topic if manually looking up manifests in NATS.
Tested on …
=> feat(multitenant)! Account prefixed API topics and manifest storage

.github/workflows/release.yml
This PR fixes the canary release image not including the wadm binaries, due to missing configuration in the release action.
N/A
`canary`
=> fix(canary): include context and binaries for canary release

Cargo.lock, Cargo.toml
This PR bumps the wadm version to 0.5.0-alpha.1 as we prepare to test new features, bug fixes, and improvements before the official 0.5.0 release.
=> chore(*): bump version to 0.5.0-alpha.1

.github/CODEOWNERS
Added CODEOWNERS files so we automatically tag reviewers on PRs.
=> chore: add CODEOWNERS for reviewers

Cargo.lock, Cargo.toml, bin/main.rs, src/consumers/manager.rs, src/server/storage.rs, src/workers/event.rs
This PR fixes two issues
1. As outlined in #129, we had issues with fully deleting all versions of a manifest and then putting that manifest again, this is both fixed by my filter to ensure we only `update` if revision > 0 and adding the jetstream domain to the purge operation
2. For a non-multitenant wadm and multitenant wadm that share the same NATS infrastructure, avoid creating consumers that will automatically fail.
Fixes #129 
Depends on https://github.com/nats-io/nats.rs/pull/1055
v0.5.0
=> fix(*): support deleting all versions of manifest

Cargo.lock, Cargo.toml, bin/main.rs, src/consumers/manager.rs
Signed-off-by: Brooks Townsend <brooks@cosmonic.com>
The problem with the current implementation is that consumers acquire permits _before_ knowing that work needs to be done. This PR is a simple refactor that ensures that all consumers are awaiting their next message on the stream, and then once they receive the next message they attempt to acquire the permit.
This PR also updates the control interface to 0.28.1, which includes a small bug fix for querying claims when a version field may be null.
N/A
v0.5.0-alpha.2
This simply makes wadm operate as intended.
I made sure this works with the default values with more than 256 consumers.
=> fix(*): acquire permit for work after receive msg

.gitignore, Cargo.lock, Cargo.toml, Makefile, bin/main.rs, bin/nats.rs, src/lib.rs, src/model/internal.rs, src/nats_utils.rs, src/scaler/manager.rs, src/scaler/mod.rs, src/scaler/simplescaler.rs, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/server/handlers.rs, src/server/mod.rs, src/server/storage.rs, src/server/types.rs, src/workers/event.rs, src/workers/event_helpers.rs, tests/api_model_operations.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/e2e_multitenant.rs, tests/event_consumer_integration.rs, tests/helpers.rs
This PR implements status for applications by adding a `status` function on the `Scaler` trait, and modifying the status accordingly. The `Undeployed` status is applied by default when a new model is put, or when the model is undeployed after deployment.
The way we calculate status is effectively a little state machine
1. When manifest deployed, set to `Compensating` as initial commands are sent out
2. After the initial set of expected events is received, ask the scaler to reconcile. 
3. If reconciliation returns commands, stay in `Compensating` state and publish those commands, and if the commands list is empty continue.
4. When commands are empty from a scaler, request the status from that scaler. The actor and provider spreadscalers are considered `Ready` if all of the spreads are …
=> feat(status): implement status for applications

.github/workflows/e2e.yml, Makefile, README.md, src/scaler/manager.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/server/handlers.rs, src/workers/event.rs, test/data/outdatedapp.yaml, test/data/upgradedapp.yaml, test/docker-compose-e2e-upgrade.yaml, tests/api_model_operations.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/e2e_multitenant.rs, tests/e2e_upgrades.rs
This PR changes the manifest deployment logic to look at old scaler components, compare them to new components, and cleanup the resources if the components no longer exist. Refer to the example in #145 for when this is appropriate.
This PR also (in the second commit) implements version upgrades by considering Actor and Provider spreadscalers meaningfully different if their image reference is different. Doing this upgrade properly _does_ seem to depend on a short delay between cleaning up old resources and starting new ones, and before this PR is accepted I'd like to resolve that instead of sleeping. Ideally, I would like to proceed with reconciliation immediately and _only_ reconcile commands for scalers that are completely new, allowing scalers to instead launch new resources based off …
=> feat: manifest and application upgrades

Dockerfile
Need to run CA Certs update for wadm to work with NGS
I dont have docker on this machine, so im letting CI sanity check it
=> add certs back

.github/workflows/e2e.yml, .github/workflows/test.yml, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/server/types.rs, src/workers/event.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/e2e_multitenant.rs, tests/e2e_upgrades.rs
Fixes https://github.com/wasmCloud/wadm/issues/149
This PR is a simplification of the status algorithm which should make manifest statuses more consistently correct. Essentially, when an event gets handled by a set of scalers, it follows this flow:
This is a little less efficient in terms of calculating the exact status of an individual scaler and publishing updates based on that, but it's simple for now and we can improve the algorithm as we see a good opportunity to do so. If you only ever ran one wadm instance this PR wouldn't be necessary, but as you can see from our e2e tests it results in a lot of flakiness when running multiple instances. Storing an internal property of `status` in a scaler works nice as long as that scaler is handling all of the relevant events, which when running …
=> feat(status): Fully compute status when publishing status updates

Cargo.lock, Cargo.toml
Bump to 0.5.0-alpha.4 to release manifest status fixes
=> chore: bump to 0.5.0-alpha.4

src/events/data.rs, src/scaler/simplescaler.rs, src/workers/event.rs
Technically the revision and the version information is _optional_ on actor claims, and if it was omitted wadm would fail to properly store actor information on startup. This PR just correctly sets these to optional and will not bork when omitted.
N/A
v0.50.
I tested that this worked properly to store state with an actor that did not contain any version or revision information, reproduced by signing an actor with `wash claims sign ./echo.wasm --name echo` which results in all the defaults.
=> fix(*): set actor revision and version to be optional

src/model/mod.rs, src/scaler/daemonscaler/mod.rs, src/scaler/daemonscaler/provider.rs, src/scaler/manager.rs, src/scaler/mod.rs, src/scaler/spreadscaler/mod.rs
This PR adds a new scaler type, the `daemonscaler`, which is a drop-in replacement for the `spreadscaler` trait. Instead of spreading a certain number of replicas across a specified set of constraints, the `daemonscaler` spreads a certain number of replicas across _all_ hosts in a lattice that match the requirements of the spread.
Kubernetes developers can think of a Spreadscaler as a k8s deployment with label selectors, and the Daemonscaler as a k8s DaemonSet (with optional label selectors)
More documentation will be needed here (PR forthcoming), but just so you know:
1. The daemonscaler uses the exact same config as the spreadscaler
2. Both daemonscalers ignore `weight` entirely
3. The provider spreadscaler ignores the `replicas` field, as you can only run one copy of a provider per …
=> Add Actor and Provider Daemonscalers

src/server/storage.rs
updates app listing to be sorted on model name
closes #156
next
anyone listing models with wadm will now have a default sort applied
None added, but happy to implement with the right pointers
None added, but happy to add
None added, but happy to add
Ran wadm build against sample app and saw a stable sort on repeated invocations
=> fix: implement model name sort in model listing

bin/logging.rs
configures the log layer to have an appropriate FormatFields when using json, or uses the default Full configuration
Crashing when running  WADM_TRACING_ENABLED=true WADM_STRUCTURED_LOGGING=true RUST_LOG=debug RUST_BACKTRACE=1 cargo run --features cli --bin wadm
```sh
WADM_TRACING_ENABLED=true WADM_STRUCTURED_LOGGING=true cargo run --features cli --bin wadm
Running `target/debug/wadm`
RUST_LOG was not set or the given directive was invalid: FromEnvError { kind: Env(NotPresent) }
Defaulting logger to `info` level
{"timestamp":"2023-09-12T14:33:16.518961Z","level":"INFO","fields":{"message":"event: connected"},"target":"async_nats::options"}
thread 'main' panicked at 'span 'new' had malformed fields! this is a bug.
error: EOF while parsing a value at line 1 column 0
fields: FormattedFields …
```
=> bug: fix structured logging crash

src/scaler/spreadscaler/mod.rs
The existing implementation of [compute_spread](https://github.com/wasmCloud/wadm/blob/1bc07979d0e09ff05e4a5a093d785b6f430fb67e/src/scaler/spreadscaler/mod.rs#L349) favors spread requirements defined earlier in the YAML, rather than the ones with the highest weight. With the updated implementation, leftover replicas are distributed based on weight.
Addresses [#154](https://github.com/wasmCloud/wadm/issues/154)
v0.6.0
N/A
The following tests are modified to align with the new implementation where order by weight does matter.
- [can_spread_properly](https://github.com/wasmCloud/wadm/blob/1bc07979d0e09ff05e4a5a093d785b6f430fb67e/src/scaler/spreadscaler/mod.rs#L438)
- [can_compute_spread_commands](https://github.com/wasmCloud/wadm/blob/1bc07979d0e09ff …
=> feat(spreadscaler): Assign leftover instances by weight, instead of spread order

src/server/handlers.rs, test/data/missing_capability_component.yaml
Today it's totally valid to define a `linkdef` with a target that's not specified.
```yaml
- type: linkdef
properties:
target: httpserver-notreal
```
When there is no capability component with name `httpserver-not-real`, manifest validation should return an appropriate error.
#179
v0.6.0
better DX
[test_manifest_validation](https://github.com/ahmedtadde/wadm/blob/786ca22424b1b4cc8b1ec192c88e85baa873edd7/src/server/handlers.rs#L936) was updated to include ensure all declared linkdef targets can be mapped to some capability component.
=> Validate that linkdef targets actually exist in the manifest

src/scaler/manager.rs, src/workers/event.rs
on [handle_manifest_published](https://github.com/ahmedtadde/wadm/blob/261dae2604fa65fb00f070a34de5c0b40809ce65/src/workers/event.rs#L756) the scaler components are extracted twice from the manifest. First to compute the difference between the old (previously added to the ScalerManager) and the ones in the manifest received. It is then computed again in order to actually add the ones in the manifest received to the ScalerManager.
#161 
v.0.6.0
n/a
=> Refactor manifest upgrade for more efficient scaler computation 

Cargo.lock, Cargo.toml, oam/oam.schema.json, src/server/handlers.rs, test/data/incorrect_component.yaml
@lachieh @brooksmtownsend 
FEAT : A[ json schema](https://json-schema.org) for validating the format of manifests
#122 #123 #176 
next
Incorrect manifests would be rejected by the system
All test cases for current manifests pass. Also validated against an [online validator](https://www.jsonschemavalidator.net).
NA
NA
manually verified
=> Add JSON schema validation for OAM manifests

Cargo.lock, Cargo.toml
Bumping to 0.7.1 to "officially" release 0.7.0, unfortunately I made a mistake in cutting the RC and we'll want to yank the crate 0.7.0.
=> chore: bump to 0.7.1

bin/main.rs
currently, one can't have a separate stream for different wadms' running in a multitenant environment (e.g. wadm_status).
#180
v0.7.x
adds some flexibility to `wadm`
=> [FEAT] Add the ability to set a stream prefix for all wadm internal streams 

bin/main.rs, src/model/mod.rs, src/scaler/daemonscaler/provider.rs, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/provider.rs, test/data/upgradedapp2.yaml, tests/e2e_upgrades.rs
Currently, the check to ensure that a scaler is meaningfully different from a previous version is done by comparing the IDs to each other. However, the ID for a link scaler does not include its values, and the ID for a provider scaler does not include its provider config. We should generate some form of short hash of linkdef values and provider and append that to the ID so we can delete + put a link, or stop + start a provider when the configuration changes.
#159 
v0.7.0
improved correctness for `wadm` manifest change detection
=> [FEAT] Support upgrades of just link config or provider config

src/server/handlers.rs, test/data/duplicate_imageref1.yaml, test/data/upgradedapp3.yaml, tests/e2e_upgrades.rs
Bug: Providers deployed in a manifest on a link name needed to have a unique image reference associated with it. This allowed for providers with the same reference but different versions to be created on the same link name. 
Fix: This PR improves upon this issue by associating an image ref, regardless of the version, with a link name. By ignoring the version, we permit only unique image references into the manifest/lattice.
next
Capabilities with duplicate image refs will be removed.
manually tested
Modified `test_manifest_validation`
Updated e2e test named `e2e_upgrades` to check for provider versioning
manually verified.
=> Modified provider checks to be version independant

.gitignore, src/workers/event.rs
This PR adds additional logic to the host heartbeat handling to make sure that actors and providers fully reconstitute state from heartbeats, even if the `wadm_state` bucket was entirely deleted. Wadm currently restores _most_ critical information, but notably did not restore the image reference which would require you to delete and restart the actor or provider in order for wadm to find it.
Mentioned #191 in the code here.
I think we should take out a release branch to publish a patch for 0.7.2 with this commit at least cherry picked in order to not hold this back on 0.8.0.
Updated the heartbeat missing information test to actually test that we restore _all_ data.
I tested this both with partial information and an entirely deleted `wadm_state` …
=> Fully reconstitute state from heartbeats

Cargo.lock, Cargo.toml, src/workers/event.rs
This PR ensures the last bit of information there is to gleam from the host heartbeat, the provider annotations, updates the providers list in the host state store.
#199 
v0.8.0-rc.3
Updated unit test with host assertion and annotation assertion to be doubly sure.
=> fix: update stored host provider annotations

oam/oam.schema.json, src/server/handlers.rs, test/data/long_image_refs.yaml
Sometimes, sufficiently nested folders will require a length longer than 128 characters for the path to a Wasm executable, when using the `file://` specifier.
While it's questionable whether the image should be limited at all, it looks like 128 is at the very least too low.
This commit increases the string allowed for `image` specification to a higher multiple of 128.
=> fix: increase length to 512 for image references

Cargo.lock, Cargo.toml
This PR just bumps to v0.8.0 once we're ready to release officially
=> chore: bump to v0.8.0

src/scaler/manager.rs, src/storage/mod.rs, src/storage/snapshot.rs, src/workers/event.rs
This works by looking up all the data once per event (whenever scalers are called). This reduces lookups of links by at least 40% and should reduce data usage as well (though not as much as doing some sort of caching would)
Comparing number of `get.links` requests coming over the control topics:
```
❯
rg 'get.links' /tmp/test-e2e-after | wc -l
272
❯
rg 'get.links' /tmp/test-e2e-before | wc -l
459
```
Fixes #203
=> fix(storage): Updates scalers to do a single data lookup per event

src/server/handlers.rs
Better error messages for JSON validation.
Currently, when manifests are validated, the deserialization and validation is internally  handled by serde and it prints out error messages that specify the exact location of the error in the file. Here are some of the errors thrown by serde:
```
Should be able to parse: spec.components[5]: missing field `contract` at line 97 column 7
Should be able to parse: spec.components[0]: invalid type: unit value, expected struct ActorProperties at line 10 column 7
```
Serde handles a majority of the cases in the `Manifest` schema but in the case of `Traits`,  if there are any missing or incorrect properties that do not fall under type `Linkedef` or `Spreadscaler`, serde deserializes to `Custom` `TraitProperty`.  Upon which the validation falls through to …
=> chore: Better JSON validation error messages

Cargo.lock, Cargo.toml
This PR bumps to 0.9.0 to release dependency updates in #218
=> chore: bump to 0.9.0

src/server/types.rs
`DeleteResult` enum is missing `PartialEq` and `Eq`, which seem to be implemented for all of the other `<Operation>Result` types.
=> Derive PartialEq and Eq for DeleteResult

bin/main.rs, src/scaler/daemonscaler/mod.rs, src/scaler/spreadscaler/mod.rs, src/workers/event.rs, src/workers/event_helpers.rs
This PR adds a simple check before publishing a status to query the previous status and skip publishing if it would be the exact same. This should quiet down the status stream quite a bit for already deployed applications and it should make it a lot easier to follow during debugging.
Fixes #187 
`next` release, can be a patch.
This PR does add a burden on the status stream with a stream get
The status stream was much less noisy during e2e tests, for example during the upgrade e2e test the number of status messages went from 57 to 23. This is impressive as this PR isn't primarily concerned with reducing the number during deployment, we just end up publishing a lot of duplicate statuses.
=> feat(status): prevent duplicate status publishes

.github/workflows/release.yml
This PR fixes an issue where we were storing a token as a secret and then referencing it rather than using the implicit GITHUB_TOKEN.
=> chore: updated release github token

src/model/mod.rs, src/workers/event.rs
=> chore: addressed clippy warnings rust 1.74

README.md, oam/README.md, oam/custom.yaml, oam/echo.yaml, oam/oam.schema.json, oam/petclinic.yaml, oam/simple1.json, oam/simple2.yaml, src/model/mod.rs, src/scaler/daemonscaler/mod.rs, src/scaler/daemonscaler/provider.rs, src/scaler/manager.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, test/data/all_hosts.yaml, test/data/complex.yaml, test/data/duplicate_component.yaml, test/data/duplicate_imageref1.yaml, test/data/duplicate_imageref2.yaml, test/data/duplicate_linkdef.yaml, test/data/host_stop.yaml, test/data/incorrect_component.yaml, test/data/long_image_refs.yaml, test/data/lotta_actors.yaml, test/data/missing_capability_component.yaml, test/data/outdatedapp.yaml, test/data/simple.yaml, test/data/simple2.yaml, test/data/upgradedapp.yaml, test/data/upgradedapp2.yaml
This PR updates the manifest definition to refer to replicas of actors and providers as `instances`, rather than simply `replicas`. After the change to the host to effectively autoscale to a maximum concurrent load, we aren't really spreading replicas around like we used to.
I acknowledge this is a little awkward when it comes to having an underscore in a yaml property, and the fact that this doesn't really make as much sense for capability providers. For that reason this is a change that's mostly internal, and you can still use `replicas` as the property for now. In the future, I would love to rethink this trait property and how it pertains to  our scaling model. With capability providers being WASI-based, it may make sense to use this concurrency property for providers too.
Changes in …
=> feat(model): max_concurrent instead of replicas

Cargo.lock, Cargo.toml, src/commands/mod.rs, src/scaler/manager.rs
This PR removes the `BackoffAwareScaler` wrapper around Actor and link scalers as it is not a useful addition to the scaler logic. Both actor and link scalers issue idempotent commands and actor scalers actually haven't utilized the backoff functionality since #171. In some cases we even see linkdef scalers looping infinitely so this should fix that. 
#171
v0.9.2 with a cherry pick
=> fix(scaler): remove backoff wrapper around link

Cargo.lock
We currently have `wasm-bindgen` locked at `0.2.88`, but [that version was yanked](https://lib.rs/crates/wasm-bindgen/versions), so let's depend on `0.2.89` instead.
=> chore: Update wasm-bindgen version

Cargo.lock
This updates `serde_yaml` to latest version of `0.9` to bring in `unsafe-libyaml` `0.2.10`, which addresses [RUSTSEC-2023-0075](https://rustsec.org/advisories/RUSTSEC-2023-0075) and [GHSA-r24f-hg58-vfrw](https://github.com/advisories/GHSA-r24f-hg58-vfrw)
=> chore: Update serde_yaml version to bump unsafe-libyaml

Cargo.lock, Cargo.toml, bin/logging.rs
As best as I can tell, [`atty` is unmaintained](https://github.com/softprops/atty/), which is unfortunate because it has an outstanding security vulnerability ([RUSTSEC-2021-0145](https://rustsec.org/advisories/RUSTSEC-2021-0145) / [GHSA-g98v-hv3f-hcfr](https://github.com/advisories/GHSA-g98v-hv3f-hcfr)).
Fortunately, [Rust 1.70.0 shipped native functionality to replace what `atty` was providing](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#isterminal).
I might've missed it, since I don't believe we have a defined msrv, I think expecting Rust 1.70.0 for this functionality seems fair.
If this is a bad assumption or we absolutely insist on supporting [Hermit](https://github.com/hermit-os), we should at least consider switching from `atty` to …
=> chore: Replace atty with std::io::IsTerminal

src/scaler/manager.rs
This PR fixes a possible issue where, in the case where a single wadm instance doesn't find scalers for a particular manifest name, it won't notify the other instances to delete those scalers as well. After this fix, anytime we request to remove scalers (which is only when a manifest is undeployed) we will send the `DeleteScalers` notification to each instance.
Can be a patch release cherry picked for 0.9.2, or just pushed into 0.10.0.
=> fix(scaler): always publish delete notification

src/scaler/daemonscaler/mod.rs, src/scaler/daemonscaler/provider.rs, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/server/types.rs, src/workers/event.rs
This PR resolves a problematic infinite loop when it comes to link scalers. In rare cases it's possible for a link scaler to receive a `LinkdefSet` event for its own link definition, but when it goes to query the list of link definitions nothing comes back. This is an external problem to wadm, usually manifesting if a host fails to respond in time, but in this case the link scaler will publish a command to set the link definition and then will trigger a `LinkdefSet` event ➿.
This PR simply shortens this feedback loop to doing what is intended, when a link scaler receives the `LinkdefSet` event and it matches all of its configuration parameters, it updates its internal status to `Deployed`. 
This is a temporary patch, #206 should make this unnecessary but there's no harm in keeping this …
=> fix(scaler): resolve possible linkdef loop

bin/connections.rs, bin/observer.rs, src/lib.rs, src/nats_utils.rs, test/nats/nats-test.conf, tests/command_worker_integration.rs, tests/event_consumer_integration.rs
The wasmCloud host now emits events on `wasmbus.evt.{lattice-id}.{event-type}`, so this updates wadm to use the suffixed subject
~Next. Not a breaking change, so maybe v0.10.1?~
v0.11.0
N/A
Updated existing tests
=> feat(*): subscribe to updated lattice event subjects

bin/main.rs, bin/nats.rs
NATS servers support TLS, which means sometimes you need to be able to provide certificates when instantiating a client.
This specifically adds support for supplying a CA certificate to use when connecting to a NATS server. I opted not to add client certificate support for mTLS for now, but it's an easy lift if it should just be added now.
Tested locally using a NATS server with a self-signed CA and cert. Everything worked fine
=> feat: support TLS CA certificates when building a NATS client

bin/logging.rs, bin/main.rs
OTEL changed it's default port from 55680/55681 to 4317/4318 for [gRPC](https://opentelemetry.io/docs/specs/otlp/#otlpgrpc-default-port) and [HTTP](https://opentelemetry.io/docs/specs/otlp/#otlphttp-default-port) respectively [a while back in the spec](https://github.com/open-telemetry/opentelemetry-specification/pull/1839) and [in the collector](https://github.com/open-telemetry/opentelemetry-collector/pull/3743), let's switch over to using the current ports defined in the spec.
=> chore: Update the default OTLP HTTP port to match the current OTEL spec

src/events/types.rs, src/storage/state.rs, src/workers/event.rs, test/data/events.json, tests/command_worker_integration.rs, tests/event_consumer_integration.rs
This PR adds a handler for the actor_scaled event which will be able to summarize all of the information in `actors_started` and `actors_stopped` with an idempotent event.
Though there's future work to really make this work with v0.82, this can be released at any time without problems as the event doesn't exist yet.
Requires https://github.com/wasmCloud/wasmCloud/pull/1336
Filed #239 to cover future work that can't be done today.
v0.11.0
Note that, if testing with the unreleased v0.82.0, this may cause duplicate state updates because both the actors_started and actor_scaled events will be handled. I'll be creating an issue shortly to cover this update.
I modified the `test_all_state` function to ensure functionality around starting/stopping/scaling up/down actors.
=> feat(events): support actor_scaled event

.github/workflows/chart.yml, charts/wadm/.helmignore, charts/wadm/Chart.yaml, charts/wadm/ci/install-values.yaml, charts/wadm/ct.yaml, charts/wadm/templates/_helpers.tpl, charts/wadm/templates/deployment.yaml, charts/wadm/values.yaml
This adds a helm chart for deploying wadm on Kubernetes
=> feat: Add helm chart for deploying wadm on Kubernetes

oam/kvcounter.yaml, src/model/mod.rs, src/server/handlers.rs, test/data/simple.yaml
This PR adds supports for serializing the labels in a manifest and validating that they are correct according to the kubernetes label specification, which also matches the OAM specification.
Fixes #249 
Next wadm
Added unit test to sanity check validation rules.
With a manifest:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
name: kvcounter-rust
annotations:
version: v0.0.1
description: "Kvcounter demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
labels:
app.kubernetes.io/name: kvcounter-rust
spec:
```
The requested spec comes back as (including the label):
```bash
➜ nats req "wadm.api.default.model.get.kvcounter-rust" '{}'
17:15:21 Sending request on "wadm.api.default.model.get.kvcounter-rust"
17:15:21 Received with rtt …
```
=> feat(model): support labels in manifest

src/storage/state.rs
This PR adds a simple serde alias to let wadm handle state from a host that was stored with the "actors" field instead of "components"
`next`
=> fix(state): allow actor alias for compat

Cargo.lock, Cargo.toml, src/scaler/daemonscaler/mod.rs, src/scaler/daemonscaler/provider.rs, src/scaler/spreadscaler/link.rs, src/scaler/spreadscaler/mod.rs, src/scaler/spreadscaler/provider.rs, src/workers/event.rs
- **fix(link): issue where delete didn't trigger put**
- **fix(scaler): remove ineligible components**
- **fix(scaler): remove ineligible providers**
- **chore: bump to v0.11.0-alpha.3**
This PR fixes two issues found during alpha testing with v0.11.0
1. Fix issue where the comparison was wrong and deleting a link was not triggering the re-put of that link
1. Fix issue where scalers ignored hosts that were ineligible for their spread requirements. This most easily manifested when moving from one version of an application to another where the spread requirements changed. Since scalers only were concerned with the hosts that matched their requirements, if they previously started components on now "ineligible" hosts they would not remove them. This should make the scalers much better at …
=> Fixes from alpha2 testing, bump to alpha3

Cargo.lock, Cargo.toml, oam/config.yaml, src/commands/mod.rs, src/events/types.rs, src/scaler/configscaler.rs, src/scaler/manager.rs, src/scaler/mod.rs, src/server/handlers.rs, src/storage/snapshot.rs, src/storage/state.rs, src/test_util.rs, src/workers/command.rs, src/workers/event.rs, src/workers/event_helpers.rs, src/workers/mod.rs, test/data/complex.yaml, test/data/events.json, test/data/lotta_actors.yaml, test/data/simple.yaml, tests/e2e_multiple_hosts.rs
I would recommend taking a look at this PR commit by commit, as removing an old event, adding support for a new event, and adding configuration management are very different. If desired, I can split these out into separate PRs.
This PR implements configuration management in wadm with the use of a `ConfigScaler`. Any scalers that depend on configuration will first delegate to their set of `ConfigScaler`s to reconcile and handle events, so that all configuration can be in place, and then the component/provider/link scaler will be able to reach desired state. This is implemented making heavier use of the BackoffAwareScaler (rename pending) and will be nice when we get around to #253.
This is specifically ordered to put all configuration first before running resources as this configuration is …
=> feat: named configuration management

Cargo.lock, Cargo.toml, src/events/data.rs
This PR fixes an issue where state stored by an older version of wadm+wasmcloud(0.82) would cause trouble in event handling by repeatedly nacking failing to deserialize an event.
Fixes #269
=> fix: Provider state handling from 0.82

charts/wadm/Chart.yaml, charts/wadm/templates/_helpers.tpl
A refactoring resulted in the `WADM_NATS_CREDS_FILE` not being added when a `creds.secretName` is presented, which in turn results in the secret being correctly mounted, but not actually being used by wadm.
=> Fix rendering WADM_NATS_CREDS_FILE when creds secret is provided

.github/workflows/release.yml
This PR fixes an issue where the github runner `macos-latest` is now natively on arm64, so we need to pin to macos-13 in order to build amd64. This does simplify our release process, and natively building on the arm64 machine is great.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
https://github.com/wasmCloud/wasmCloud/issues/2134
Re-release wadm v0.11.1. I plan to cherry-pick this commit from the v0.11.1 tag to re-release this
=> ci(release): use native macos arm64 runner

src/model/mod.rs, src/model/validation.rs, src/scaler/spreadscaler/mod.rs, src/server/handlers.rs, tests/fixtures/manifests/custom-interface.wadm.yaml, tests/fixtures/manifests/dangling-link.wadm.yaml, tests/fixtures/manifests/misnamed-interface.wadm.yaml, tests/fixtures/manifests/simple.wadm.yaml, tests/fixtures/manifests/unknown-package.wadm.yaml, tests/validation.rs
This commit adds validation functions along with utility accessors to `Manifest` to enable checking WADM manifests for common errors.
As the validation functions are exposed they can be used by downstream crates (ex. `wash`) to validate WADM manifests or try to catch errors *before* a manifest is used.
This is up for review in draft state so we can talk about the design -- if it looks good, I'll do the following:
https://github.com/wasmCloud/wasmCloud/issues/2009
`next`
Unit tests with fixtures have been added
=> feat(validation): add manifest validation

.github/workflows/test.yml, crates/wadm/oam.schema.json, crates/wadm/src/server/handlers.rs
This also adds a check to make sure that the two schemas are in sync since I had to copy it over. Using something like a build.rs would have had the same issue in that the file was outside of the crate
=> fix(wadm): Adds oam schema to wadm crate

crates/wadm/src/server/handlers.rs
Update wasmcloud deployment manager to allow reuse of capability providers across deployments.
(https://github.com/wasmCloud/wadm/issues/296)
=> feat(reuseProviders): Allow capability providers to be reused across components

crates/wadm/src/server/handlers.rs
This commit removes the check that prevented making multiple links to the same target.
Resolves https://github.com/wasmCloud/wadm/issues/296
=> fix(validation): allow multiple links to the same target

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-client/src/lib.rs, crates/wadm/src/scaler/spreadscaler/provider.rs, crates/wadm/src/storage/state.rs, src/logging.rs
=> chore(deps): remove once_cell

crates/wadm/src/server/handlers.rs
Previously the `PutModelResponse` would be empty string if the incoming manifest did not already contain a version, because the version gets generated inside of the `StoredManifests.add_version(...)` function before being inserted into the IndexMap.
=> fix(wadm): Set PutModelResponse current_version based on the StoredManifests current_version

.github/workflows/e2e.yml, Makefile, crates/wadm/src/storage/mod.rs, crates/wadm/src/storage/nats_kv.rs, crates/wadm/src/test_util.rs, tests/command_worker_integration.rs, tests/e2e_upgrades.rs
This adds retries for putting state into a bucket. It is fairly basic but it gets the job done. We had to add a few more constraints to the `Store` trait to handle the retries (such as cloning data).
=> feat(state): retry state updates

README.md
Fixing wadm reference link ( wasmcloud.dev vs wasmcloud.com )
Markdown linting quotes ✨ (single occurrence!)
=> docs: Updating wadm links

crates/wadm/src/scaler/secretscaler.rs
In #307 we introduced secrets support, which works by storing secrets references as config in NATS KV. This fixes a bug in the way that we were serializing the configuration as JSON where we were overwriting the policy field which is required.
0.13.0
=> fix: write out policy data in a secret config correctly

crates/wadm-types/src/lib.rs, crates/wadm-types/src/validation.rs, crates/wadm/src/scaler/secretscaler.rs
It turns out that it is easier to parse a serialized secrets value if we have the `backend` key at the top level instead of nested in string-encoded JSON. This moves that value out of the policy properties value that the secrets scaler serializes into a config value and instead stores it as a top level key.
0.13.0
=> fix: copy backend key to top level in a generated config value

crates/wadm-types/src/validation.rs
It turns out that boolean negations are important, so use the correct check to validate that a `backend` key is missing from a policy properties block.
0.13.0
=> fix: correctly emit a validation error if a backend key in a policy is missing

crates/wadm/src/server/handlers.rs
This PR addresses the verbage in wadm's server handlers module, ensuring that we refer to operations on the wadm API as operations that create/read/update/delete Applications, not Manifests or Models. This gets closer to the verbage we use in wash-cli, and is more intuitive.
I considered splitting the verbs between Application and Manifest, and removing Model, so if any of the usage of Application feels weird let me know.
=> chore(wadm): use application verbage instead of model

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml, crates/wadm-types/src/lib.rs, crates/wadm/Cargo.toml, crates/wadm/src/scaler/secretscaler.rs, crates/wadm/src/workers/event.rs, crates/wadm/src/workers/event_helpers.rs
This PR adds in support for specifying a `field` in the secret property.
See https://github.com/wasmCloud/wasmCloud/pull/2634 for context.
wadm v0.13.0-beta.2
types/client v0.2.0-beta.2
=> feat(*): support field on secret property

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml, crates/wadm/Cargo.toml
This PR removes the beta tags, which probably should've been RCs, to prepare wadm for an 0.13.0 release.
wadm 0.13.0
types, client 0.2.0
=> chore: remove beta, pin to stable version

Cargo.lock, Cargo.toml, crates/wadm/Cargo.toml, crates/wadm/src/scaler/mod.rs
- **fix(wadm): react to config events**
- **chore(wadm): bump to 0.13.1**
This PR fixes an issue where the logic to send config or secrets commands was incorrect, resulting in configuration getting out of sync if manually deleted.
wadm 0.13.1
=> fix: react to configuration events

tests/api_model_operations.rs, tests/command_consumer_integration.rs, tests/command_worker_integration.rs, tests/event_consumer_integration.rs, tests/helpers.rs, tests/storage_nats_kv.rs
Since #367 introduced a `testcontainers`-based setup for the test environment, which provides some nice properties over running a shared NATS server, we should adopt it for more tests.
=> chore: Migrate more tests over to using testcontainers for setup

crates/wadm-client/src/lib.rs, crates/wadm-types/src/api.rs, crates/wadm/src/server/handlers.rs
This PR is a simple fix to return the name and version of a deployed manifest with the DeployModelResponse, which assists with the data that clients can use to know what version was deployed even if one wasn't supplied.
=> feat(client)!: return name and version from deploy model

src/main.rs
In the case where state reports a host but it's actually no longer running, I think we should wait only 60 seconds before considering it disconnected. This gives enough time to miss a heartbeat, but if you miss two then the scalers should recalculate.
Open to thoughts here & if there's a smarter way to do this. This mostly affects the development cycle where you are launching and tearing down wadm repeatedly. However, I would rather set configuration in an environment where hosts are known to often be disconnected to a higher value than have to configure this down for regular applications.
=> feat(wadm)!: set cleanup interval to 60s

crates/wadm/src/consumers/commands.rs, crates/wadm/src/consumers/events.rs, crates/wadm/src/consumers/manager.rs, crates/wadm/src/consumers/mod.rs
This PR resolves a comment we had in the codebase for waiting for NATS 2.10, by attaching the lattice and multitenant prefix to the consumer instead of trying to always derive it from the consumer name.
This is entirely backwards compatible, and the metadata will just be ignored if the consumer already exists. Deleting the consumer and restarting wadm is all you need to bring it in so this will likely happen naturally.
next wadm
=> fix(wadm): attach lattice/multitenant to consumer metadata

crates/wadm/src/scaler/manager.rs
This PR reorders the order of operations during cleanup to ensure that we remove the scalers from the list that will be reconciling/handling events immediately before refreshing data & publishing cleanup commands. This should help us avoid race conditions in tests and make the scalers do a better job at cleaning up.
Fixes #317
~Added a temporary commit that I'll remove that just runs the e2e tests 10 times and should serve as a good indicator if we have the issue still.~
As you can see by https://github.com/wasmCloud/wadm/actions/runs/10271223819, 10x runs of the integration tests didn't hit the condition after this
=> fix(scalers): remove scalers upon notification

src/main.rs
This PR slightly bumps the 60s cleanup interval to 70s, since the reaper will divide that by 2 and then expect to see an event in that interval. Bumping to 70s allows for 5 seconds of wiggle room to miss a heartbeat, while waiting 70s certainly means that a host missed 2 heartbeats.
=> fix(wadm): update reaper to allow for latency

crates/wadm/src/scaler/spreadscaler/link.rs
This PR adds a very simple additional check in the link scaler to ensure that if a component starts that is involved in a link where it's the target of the link, it will trigger creation of the link.
This is pretty much just a logical error to not include this.
=> fix(scalers): put link for component as target

charts/wadm/Chart.yaml, charts/wadm/templates/deployment.yaml
Rendering this chart without this fix results in an empty field for replicas.
replicasCount doesn't exist as a value so the resulting yaml looks like:
```yaml
spec:
replicas: 
selector:
```
Opted to align with the `values.yaml` which is generally treated as the primary API for a chart and thus avoids a breaking change rev.
=> fix(charts): align replicas value

crates/wadm/src/commands/mod.rs, crates/wadm/src/events/types.rs, crates/wadm/src/scaler/manager.rs, crates/wadm/src/scaler/mod.rs
This PR adds an additional field to the `BackoffWrapper` (previously BackoffAwareScaler) that can store a failed message received by wadm in response to a command. Commands in wasmCloud, particularly the ScaleComponentCommand and StartProvider command have corresponding events that indicate whether it successfully scaled/started or it failed. In this PR, I used the same structure that we already used for notifying scalers of events that should come in to also interpret whether or not a newly received event was actually a failure to process the command. In the case where the event was a failure, we now store the status in the `BackoffWrapper` and report that status for 5 seconds, effectively backing off that scaler from additional reconciliation or status reporting until that status is …
=> feat(*)!: surface application errors in status

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml, crates/wadm/Cargo.toml
This PR sets up a v0.14.0 release of wadm.
wadm v0.14.0
client v0.3.0
types v0.3.0
* **scaler:** backoff when failed event received
([7e03d06](https://github.com/wasmCloud/wadm/commit/7e03d060b311fdf73602675371efe114096a117f))
* **scaler:** implement component scale corresponding event
([f123736](https://github.com/wasmCloud/wadm/commit/f1237363c12c4ea7614badb8cfc4ceac50fc39dc))
* **scaler:** add kind and name methods
([066e50e](https://github.com/wasmCloud/wadm/commit/066e50e4eb3d284cebbb63271781f52b4297d783))
* **observer:** observe lattice on manifest publish
([19cbd5a](https://github.com/wasmCloud/wadm/commit/19cbd5a44d967f5cb5849f140004feb4022bf33d))
* **wadm:** detail status per scaler
([172db98](https://github.com/wasmCloud/wadm/commit/172db98f1e83ac33c060e9b2ac542244e5f49269))
* …
=> release: v0.14.0

crates/wadm-types/src/lib.rs, crates/wadm-types/src/validation.rs, tests/fixtures/manifests/dangling-link.wadm.yaml, tests/validation.rs
This PR seeks to catch a fairly frustrating issue where you incorrectly format a spreadscaler, daemonscaler, or link trait and all of a sudden it seems that it won't deploy. This can happen when the deserialization falls through to the Custom trait.
This PR denies any trait from having a type `spreadscaler`, `daemonscaler`, or `link` and deserialize as a custom trait. All other custom traits are supported just fine.
=> fix(wadm): ensure custom traits are not spread or link traits

Cargo.lock, Cargo.toml, crates/wadm-types/Cargo.toml, crates/wadm-types/src/bindings.rs, crates/wadm-types/src/validation.rs, crates/wadm/Cargo.toml
Our validation was erroneously rejecting things that were using the batch or watch interfaces for wasi keyvalue. Also fixes some things with versioning so we don't have to change it everywhere all the time
=> fix(types): Fixes validation for wasi:keyvalue

src/main.rs, src/nats.rs
This PR surfaces additional command line flags & environment variables for configuring the creation of NATS streams and KV buckets with a maximum amount of bytes. By default there is no limit, but depending on the NATS deployment, operators may want to (or need to) supply this parameter.
I hid these variables by default because they are very verbose, but I plan on referencing them in documentation.
=> feat(wadm)!: support configuring max stream bytes

.github/workflows/chart.yml, charts/wadm/Chart.yaml, charts/wadm/ci/ct-install-values.yaml, charts/wadm/templates/_helpers.tpl, charts/wadm/templates/deployment.yaml, charts/wadm/values.yaml
As it turns out, `127.0.0.1:4222` isn't a terribly helpful default.
Instead, the most common scenario we see today is one where wadm is installed in the same namespace as the NATS Servers running in the cluster, so we should simply attempt to use that address instead.
This behavior can still be overridden as before, by providing a value via `wadm.config.nats.server`
=> chore: Revise the default NATS Server address logic

.github/workflows/release.yml
We'd like to produce Linux `musl` binaries, so I took the opportunity to consolidate and clean up the release pipeline holistic while switching the Linux builds over from `gnu` to `musl`.
Fixes #210
=> chore: Rework release pipeline

.github/workflows/release.yml
#421 inadvertently broke Windows builds, which I suspect is related to switching to zigbuild for cross-compilation.
=> chore: Use normal cargo build on windows

.github/workflows/release.yml
Fixing up the changes from #421
=> chore: Fix up release workflow

crates/wadm/src/server/handlers.rs, crates/wadm/src/server/mod.rs
When moving to the new list operation, we also changed the type. This change ensures that older clients will, for one minor version, still be able to list applications and newer clients can migrate.
The function added in this PR, and the `list` operation handler, can be removed once we release the next version of wadm.
```
➜ wash app put ./host_stop.yaml
Put application "host-stop", version "01J8G0DW1YWTT3N8ETMSPC6V82"
on fix/deprecated-model-list 🛁 wash v0.33.0 
/private/var/folders/rf/kgpfv4t9437cj3h3c77vglrr0000gn/T/tmp.cAIkxdl8WR/tests/fixtures/manifests ➜ wash app list
Name        Deployed Version   Status      
host-stop   N/A                Undeployed  
└ This is my app
```
=> fix(handler): backwards compat list

Cargo.lock, Cargo.toml, crates/wadm/src/commands/mod.rs, crates/wadm/src/events/types.rs, crates/wadm/src/scaler/daemonscaler/mod.rs, crates/wadm/src/scaler/spreadscaler/link.rs, crates/wadm/src/scaler/spreadscaler/mod.rs, crates/wadm/src/storage/snapshot.rs, crates/wadm/src/storage/state.rs, crates/wadm/src/test_util.rs, crates/wadm/src/workers/command.rs, crates/wadm/src/workers/event.rs, crates/wadm/src/workers/event_helpers.rs, tests/command_worker_integration.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/e2e_upgrades.rs
NOTE: this branch won't compile since it's using a local reference to my local control interface v2.0.0, but once we have released `wasmcloud-control-interface` we can change that -- the changed code will be the same
=> chore(deps): update control interface to v2.0.0

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml
This brings the wasmcloud-control-interface up to `2.2.0` for these two crates.
=> release: Bump wadm-client and wadm-types to 0.6.0

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml
Because transitive deps suck. We need this so we can update the OCI deps in the main host
=> chore: Pull in slightly older version of regex

Dockerfile.wolfi
Comparing our current `wolfi-base` source (Docker Hub):
```shell
$ grype chainguard/wolfi-base:latest        
✔ Loaded image                                                                                                                                                                                                                                chainguard/wolfi-base:latest
✔ Parsed image                                                                                                                                                                                     sha256:4bf8e6d0fe675b9cfdb4e5942f1b34247c14384d0901efcc5b5299321f787f61
✔ Cataloged contents …
```
=> chore: Swap wolfi-base source to cgr.dev instead of Docker Hub

Cargo.lock, Cargo.toml, crates/wadm-types/Cargo.toml, crates/wadm-types/src/lib.rs
This upgrades `utoipa-gen` from `4.3.0` to `5.1.1`, which drops the dependency on `proc-macro-error` in order to address https://rustsec.org/advisories/RUSTSEC-2024-0370.html
=> fix(wadm-types): Address RUSTSEC-2024-0370

charts/wadm/Chart.yaml, charts/wadm/templates/deployment.yaml
Pull the `jetstreamDomain` value from `config.wadm.nats.jetstreamDomain` instead of from `config.wadm.jetstreamDomain` since that is what we define in the values file. It is also a more logical way to group the value than what the chart was expecting.
Next chart release
=> fix(chart): reference the correct value for the Jetstream domain

.github/workflows/release.yml
The PR adds support for adding the the release version tag without "v" { 0.10.0 instead of v0.10.0} to the docker images (including wolfi).
I have not removed the existing tagging logic as mentioned in the issue(needs to be keep for some time before complete migration to use the new format).
Closes #465
Note:
The specific approach suggested in [here in the issue](https://github.com/wasmCloud/wadm/issues/465#issuecomment-2442654942), doesn't work as Github Action doesn't allow[ inline string manipulation in expressions](https://stackoverflow.com/questions/62627931/github-actions-expression-functions-string-manipulation).
Github Action Run with correctly formatted tag: https://github.com/sp6370/wadm_/actions/runs/11905116268/job/33175286269
=> chore: Update the Github Action to set correct tag for the Docker Image

.github/workflows/chart.yml, .github/workflows/e2e.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/wit-wadm.yaml
=> chore(ci): Set token permissions for GitHub Actions workflows

crates/wadm/src/scaler/spreadscaler/mod.rs, tests/command_worker_integration.rs
A `ComponentSpreadScaler` config may have a set of requirements which cannot fully be satisfied so the deployment status remains as "Reconciling".
#432 
`next`
This is an enhancement/correctness change. It should have no adverse effect on existing functionality. This change prevents potential `Heisenbugs` where `wadm` could potentially operate on faulty instance spread without any detection.
All existing tests (unit and e2e) are functional
Added two test cases `can_detect_spread_requirements_violation_1` and `can_detect_spread_requirements_violation_2`
=> fix: detect spread scaler requirements violation

crates/wadm-types/src/lib.rs, crates/wadm-types/src/validation.rs, crates/wadm/src/server/handlers.rs, tests/fixtures/manifests/duplicate_links.yaml
Added a manifest validation check for "duplicate" links.
Multiple links from the same source with the same name, namespace and package are considered duplicate links.
- #445 
- Manifests that previously passed validation checks will not pass validation checks anymore if they contain duplicate links
- Modified the manifest validation tests to include a duplicate links test
- verified the output for possible cases
=> Add manifest validation check for "duplicate" links

crates/wadm/src/server/handlers.rs, tests/api_model_operations.rs
If an incorrect model name is passed without a version to the `wash app del <app_name>` command, it still outputs a success message ("Deleted application: <app_name>") even though this app does not exist.
closes #502 
This PR fixes a non-critical issue. It can therefore be safely included in the next version.
This PR adapts the lookup logic for deletion requests, so that also for non-existing models a `DeleteResult::Noop` result is returned if no version is specified. This changes the current return value (which is `DeleteResult::Deleted`).
Currently, the documented and recommended way to delete applications is to use the wadm-client crate. The wadm-client create [interprets both delete results as a success](https://docs.rs/wadm-client/latest/wadm_client/struct.Client.html#method.delete_ma …
=> fix(server): wash app delete command returns success for invalid application name

Cargo.lock, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml, crates/wadm-types/src/lib.rs, crates/wadm-types/src/validation.rs
Need to depend on wadm-types in wasm context. I added a new wasm feature flag which removes tokio as a dependency and makes the validate manifest function for a Path optional.
Can these be named better?
=> Add wasm flag for wasm targets

Cargo.lock, crates/wadm-types/src/validation.rs, tests/fixtures/manifests/duplicate_link_config_names.wadm.yaml, tests/validation.rs
If an application manifest is applied in which several link configurations have the same name, this leads to a dead loop.
closes #478
This PR fixes a problem without making any breaking changes. It can therefore be safely included in the next version.
This PR introduces an additional validation logic that prevents users to apply invalid manifests. If the manifest is valid, nothing changes for the users.
Additionally, it is planned to modify the `BackoffWrapper` and introduce an exponentially increasing delay for a retry in case of an error, which introduces longer feedback loops for (debugging) users.
An additional test case has been added for the new validation logic.
> **Note:** Further tests may be added as part of the “BackoffWrapper” modification.
=> fix(server): Added validation for duplicated link config names

crates/wadm-types/src/validation.rs, tests/fixtures/manifests/deprecated-source-and-target-config.yaml, tests/validation.rs
#288 
unit tests should cover the negative case, other validation calls don't have this error
=> feat(validation): validation fails if component has source_config

crates/wadm-types/src/api.rs, crates/wadm-types/src/bindings.rs, crates/wadm-types/wit/deps/wadm/types.wit, crates/wadm/src/scaler/daemonscaler/provider.rs, crates/wadm/src/scaler/spreadscaler/provider.rs, crates/wadm/src/storage/state.rs
Scaler status returns a `Failed` status if it contains any providers which have failed their most recent health check and are in a `Failed` state.
- #447 
Added 2 unit tests each for daemon and spread scalers
- test_unhealthy_providers_return_unhealthy_status
- test_healthy_providers_return_healthy_status
Verified the scaler status after `reconcile` is run and that all unit tests passed.
=> Reflect unhealthy providers in application status

crates/wadm-types/src/validation.rs, crates/wadm/src/server/handlers.rs, tests/fixtures/manifests/correct_unique_interface_links.yaml, tests/fixtures/manifests/incorrect_unique_interface_links.yaml
Related fix for https://github.com/wasmCloud/wasmCloud/issues/3801
=> allow unique interfaces across duplicate links and test

src/main.rs, src/nats.rs, tests/e2e.rs, tests/e2e_multiple_hosts.rs, tests/e2e_shared.rs, tests/e2e_upgrades.rs
cli toggle to modify the nats stream persistence between file and memory.
I do seek some guidance regarding testing here. Since we have multiple tests which have the file - default - mode enabled, should I create another suite or how do you think should I add tests for this?
Thank you
#479
=> feat(nats): flag to change persistence of streams

crates/wadm-types/src/validation.rs, tests/validation.rs
This PR downgrades the unrecognized interface error into a warning as inspired by some of the recent additions to keyvalue like `batch` and `watch`. We want to maintain a balance in validation to make sure that users don't accidentally link on, say, `wasi:keyvalue/atormics`, but we don't completely block the addition of new interfaces e.g. in wasmcloud:messaging@v0.3.0
Open to thoughts here.
=> fix(types): warn on unknown interface

crates/wadm-client/src/topics.rs
When generating the subscribe wadm topic, it does it incorrectly because it defaults to using the topic prefix of 'wadm.api.{lattice}'
however when subscribing to status we need to use wadm.status
After this fix, this should change:
wadm.status.wadm.api.default.my-app
to:
wadm.status.default.my-app
without affecting any other topic construction
=> fix(wadm): correct status topic name in WADM

.github/workflows/wit-wadm.yaml
wit-deps fails because the wit is in a slightly different structure,
this is a simple fix to make sure the wit is located in a /wit directory in the tarball
=> fix(ci): correct wadm WIT tarball structure

crates/wadm-types/src/validation.rs, tests/fixtures/manifests/duplicate_link_config_names.wadm.yaml
https://github.com/wasmCloud/wadm/pull/516 rejects manifests where multiple link configurations have the same name. This PR augments that functionality by only considering link configurations that declare properties. This is because (as currently implemented) configurations that don't declare properties can reference existing configs that are created either by `wash` or by `wadm` (prefixed by the application name, e.g. where application = "my-app" and config = "my-config", this can be referenced elsewhere in the manifest as "my_app-my_config").
https://github.com/wasmCloud/wadm/pull/516
https://github.com/wasmCloud/wadm/issues/478
https://github.com/wasmCloud/wadm/issues/401
Manifests that were previously rejected may now be valid. As this widens rather than narrows, I suspect it can be …
=> Only check configs for unique names if they declare properties

Cargo.lock, Cargo.toml, crates/wadm/src/scaler/daemonscaler/mod.rs, crates/wadm/src/scaler/daemonscaler/provider.rs, crates/wadm/src/scaler/spreadscaler/mod.rs, crates/wadm/src/scaler/spreadscaler/provider.rs
This PR adds a fix to component and provider scalers to ensure they react to their respective configuration set/deleted events.
Currently, on initial reconcile, the first pass is used to create configuration that's required for the component/provider to exist in the first place. Then, the idea is that the next reconciliation pass (once config is created) we would actually start the component/provider. However, today, scalers do not react to this event, so instead we sit around waiting for a heartbeat to really start the component.
I did not address the configuration set for links because links currently get created either:
1. When their provider is healthy
2. When the respective component starts
I don't want to accidentally exacerbate a race condition by adding reacting to configuration …
=> fix(scaler): react to config set events for components/providers

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml
PR to upgrade async-nats to 0.39.
Marking this as ready for review even though we're using git dependencies since ideally we merge this PR so we can start releasing wasmCloud crates and then follow this up with another PR to use the published control interface.
Depends on https://github.com/wasmCloud/wasmCloud/pull/4210 which depends on this
=> chore(async-nats)!: upgrade to 0.39

Cargo.lock, Cargo.toml, crates/wadm-client/Cargo.toml, crates/wadm-types/Cargo.toml
Now that the control client is released, we can release wadm to continue releasing the rest of the host monorepo
=> chore: Bump dep versions in preparation for release
